# Generated by Django 4.1.1 on 2022-12-08 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=5000)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.comment')),
            ],
        ),
    ]
