# Generated by Django 4.1.1 on 2022-12-09 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_replies_poster_replies_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='step',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='replies',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_list', to='wiki.comment'),
        ),
    ]
