# Generated by Django 4.1.1 on 2022-12-09 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_images_step_alter_replies_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='step',
        ),
    ]
